title: Elliot Gunn
logo: /assets/img/elliot_01.png
description: data scientist detected using YOLO, which uses a single neural network to predict objects
show_downloads: false
google_analytics: 144576790
theme: jekyll-theme-minimal
