title: Elliot Gunn
logo: /assets/img/profile_pic2.jpg
description: Data scientist in training.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

twitter:
  username               : @elliot_j_g
